### ISSUE TITLE
All JSON API Filter and Sort fields names are Case Sensitive 

### ISSUE THREAD

**Issue by tylerm007** [OntimizeWeb/northwind-jsonapi#12]
filter[FieldName] is case sensitive - 
sort[FieldName] is case sensitive

The advanced expression parser will use the models.py SQLAlchemy API field names to validate filters and sorts - these should be case sensitive and match the model. (The column list generated from app_model.yaml is also case sensitive).

**Comment by patricia-martinez-imatia** [comment]
Resolved in the version 15.1.0-JSONAPI-SNAPSHOT-8
