### ISSUE TITLE
JSON API field list should use comma seperated value

### ISSUE THREAD

**Issue by tylerm007** [OntimizeWeb/northwind-jsonapi#9]
/ontimizeweb/services/rest/Employee?fields[Employee][0]=LastName&fields[Employee][1]=OnLoanDepartmentId&fields[Employee][2]=WorksForDepartmentId&fields[Employee][3]=Salary&fields[Employee][4]=ProperSalary&fields[Employee][5]=EmployeeType&fields[Employee][6]=Dues&fields[Employee][7]=FirstName&fields[Employee][8]=Id&fields[Employee][9]=Title&fields[Employee][10]=TitleOfCourtesy&fields[Employee][11]=BirthDate&fields[Employee][12]=HireDate&fields[Employee][13]=Address&fields[Employee][14]=City&fields[Employee][15]=Region&fields[Employee][16]=PostalCode&fields[Employee][17]=Country&fields[Employee][18]=HomePhone&fields[Employee][19]=Extension&fields[Employee][20]=ReportsTo&fields[Employee][21]=PhotoPath&fields[Employee][22]=Notes&page[offset]=0&page[limit]=20& 

Should Be:
fields[Employee]=LastName,FirstName,Address,Country ....etc

**Comment by patricia-martinez-imatia** [comment]
Resolved in the version **15.1.0-JSONAPI-SNAPSHOT-8**
